### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by stderr-to-devnull** [huntertran/markdown-toc#11]
Not working, tried all context menu options, nothing is generated in my document. 4 levels of headers. Markdown checked by markdownlint extension.

**Comment by stderr-to-devnull** [comment]
Tried another one to test, it works (not very good but it does generate something): https://marketplace.visualstudio.com/items?itemName=joffreykern.markdown-toc

**Comment by huntertran** [comment]
can you provide a sample of your document?

**Comment by huntertran** [comment]
close this issue due to inative response
