### ISSUE TITLE
consecutive code blocks confuses headings

### ISSUE THREAD

**Issue by kskmori** [huntertran/markdown-toc#12]
It can not generate TOC properly with the input below which contains consecutive code blocks:

* sample input
````
<!--- TOC --->
<!--- /TOC --->

# section 1

```
# ls codeblock1
```
```
# ls codeblock2 --this is NOT a section
```

# section 2
````

* actual results
````
- [section 1](#section-1)
- [ls codeblock2 --this is NOT a section](#ls-codeblock2---this-is-not-a-section)
````

* expected results
````
- [section 1](#section-1)
- [section 2](#section-2)
````

* Analysis:

I didn't look into the code thoroughly, but `+1` to the index here does not seem to be necessary:
```
--- out.org/HeaderManager.js    2019-11-06 13:41:11.402642100 +0900
+++ out.fix/HeaderManager.js    2019-11-06 14:47:27.819139500 +0900
@@ -58,7 +58,6 @@
             while (this.isLineStartOrEndOfCodeBlock(index, doc) == false && index < doc.lineCount - 1) {
                 index = index + 1;
             }
-            return index + 1;
         }
         return index;
     }
```

 * Version:
   * Auto Markdown TOC: 3.0.1 (according to the VSCode extensions description)
   * VSCode: 1.39.2

Thanks,

**Comment by huntertran** [comment]
Thank you for reporting the bug. Currently, I busy with my studies. Any pull-request is welcome 😄
Otherwise, I will come back to this when I have spare time
