### ISSUE TITLE
Remove accents from anchor links

### ISSUE THREAD

**Issue by rolandtoth** [huntertran/markdown-toc#19]
Hi,

this extension almost works perfectly for our needs but there's one breaking issue: the generated TOC anchor links contain accents when the headings contain accents (in non-English languages).

The problem is that they don't work in Acrobat reader:

```
FAIL:
- [Bevezető](#markdown-header-bevezető)

OK:
- [Link header](#markdown-header-link-header)
```

Is there a way to clean up these special chars and replace them with normal ones? If not, please consider this as a feature request :)

**Comment by huntertran** [comment]
I'm thinking of convert all the unicode character to URL encoded or ASCII.
This will be a new feature

**Comment by rolandtoth** [comment]
Sounds great, thanks!

**Comment by huntertran** [comment]
this is implemented in 3.0.7

**Comment by rolandtoth** [comment]
In the meantime I had to fix it myself because of deadlines, and added a few other fixes as well, but thanks anyway!

**Comment by huntertran** [comment]
Ah nice. A pull request will always be welcomed ;)
