### ISSUE TITLE
Can't set bulletCharacter to *

### ISSUE THREAD

**Issue by mook-as** [huntertran/markdown-toc#21]
When using the inline options, I can't seem to set `bulletCharacter` to `*`.

Test case:

```markdown
<!-- TOC bulletCharacter:* -->
<!-- /TOC -->
# Heading
## Subheading
```

Expected results:
```markdown
* [Heading](#heading)
    * [Subheading](#subheading)
```

Actual results:
```markdown
- [Heading](#heading)
    - [Subheading](#subheading)
```

<details>
<summary>Installed extension version</summary>

```
Name: Auto Markdown TOC
Id: huntertran.auto-markdown-toc
Description: Markdown TOC (Table Of Contents) Plugin for Visual Studio Code.
Version: 3.0.3
Publisher: Hunter Tran
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=huntertran.auto-markdown-toc
```
</details>

(Apologies for the terrible initial bug report, I fat-fingered and pressed `Enter` accidentally.)

**Comment by huntertran** [comment]
Thank you for reporting the bug. Currently, I busy with my studies. Any pull-request is welcome 😄 
Otherwise, I will come back to this when I have spare time

**Comment by huntertran** [comment]
the updated code was released
