### ISSUE TITLE
Ignore some sections

### ISSUE THREAD

**Issue by ashwin-pc** [huntertran/markdown-toc#23]
Eg. 
```
# Amazing Project
## Table of Contents
## Heading 1
```

The output of this will be 
- [Amazing Project](#amazing-project)
	- [Table of Contents](#table-of-contents)
	- [Heading 1](#heading-1)

What i would like to see is
- [Amazing Project](#amazing-project)
	- [Heading 1](#heading-1)

**Comment by huntertran** [comment]
maybe an inline option?

**Comment by mwhebert** [comment]
@ashwin-pc - How would you expect this to affect numbering (orderedlist:true)?   Or the indent of headings.  Seems like this would only be usable on top level headings (one "#")

Thoughts?

**Comment by mwhebert** [comment]
Also couldn't this be done by markup like:

# Amazing Project
<h2>Table of Contents</h2>
## Heading 1

**Comment by huntertran** [comment]
I mean something like this
```
# heading 1
## heading 1.1
<!-- skipline -->
```

But currently I too busy with my studies. Any contribution will be appreciated.

**Comment by ashwin-pc** [comment]
@huntertran There already seems to be a Regex in the code for this exact reason. Ive raised a pull request to use it #27
