### ISSUE TITLE
Feature request: add extension setting to choose the number of space per indentation level

### ISSUE THREAD

**Issue by zertrin** [huntertran/markdown-toc#24]
The default indentation level the TOC is generated with is 4. But I'm actually using 2 spaces per indentation level in my documents.

It would be nice to be able to have a setting for this extension where the user can change the number of spaces per indentation level.

What do you think?

**Comment by huntertran** [comment]
actually the extension using the default tab character of VSCode

![image](https://user-images.githubusercontent.com/4468525/75811598-b8609a80-5d5a-11ea-9004-25b77699fc98.png)
