### ISSUE TITLE
Use two spaces instead of configured tab width to indent TOC

### ISSUE THREAD

**Issue by pgroke-dt** [huntertran/markdown-toc#31]
I think it would make more sense to use two spaces instead of the configured tab width for indentation when creating the TOC. Markdown says it should be two spaces, so I don't see a good reason to allow using anything else.

Of course one can fix that by configuring a tab width of 2 for markdown files. But it took me looking into the code to find out that I needed to do that. So if it's important to allow different indentation amounts, maybe this should be made a config option (which defaults to two) instead. Or, IMO also OK,  a config option that defaults to "use tab width" but can be changed to use a fixed width.

**Comment by huntertran** [comment]
![image](https://user-images.githubusercontent.com/4468525/84613542-6834c080-ae91-11ea-938f-64971f0f6eac.png)
The extension already using your default tab size for markdown language. I think implementing a setting to set custom tab size defeat the simplicity of the code.

**Comment by pgroke** [comment]
I understand that. I just don't think the configured indentation should be used for this at all. As I already wrote, Markdown says this needs to be 2 spaces, always, so using the configured indentation IMO makes no sense. If you want simple, just hard-code 2 spaces.

Having a different indentation configured can still make sense. E.g. 4 spaces if one wants to easily write code-sections by simply indenting once.

**Comment by huntertran** [comment]
Actually you can change the default tab size just for markdown in vscode.
I believe the default formatter will skip the text in code blocks.
If I hard code 2 spaces, other user who use tab character for tab, or 4 spaces will be forced to use 2 spaces. That's not how they would want. Using the default tab size is the best option.

**Comment by pgroke-dt** [comment]
I know that I can change the default tab size just for markdown. (I even wrote that this is a possible workaround in the ticket description.)

But it's a) cumbersome and b) I don't think indentation of a Markdown TOC is something that should use the configured indentation. Because indentation of Markdown is not "free form", it's required to be exactly 2 spaces. (Yes, many Markdown renderers will "forgive" this -- but some also won't, and e.g. display an ugly double-indented TOC if 4 spaces are used.)
In other parts or Markdown however, indentation of 4 spaces is more convenient, e.g. when writing code samples. So I think forcing the user to set the indentation to 2 just to get correct Markdown is wrong.

And coming back to a) cumbersome: Almost every user of this plugin who wants it to produce "correct" Markdown will have to google this one -- or even look into the actual implementation. Because 1) it's not documented that this plugin uses the configured indentation for the TOC. And it was very surprising to me, so I'd say it's also not intuitive. And 2) not everyone using VSCode actually knows how to configure the indentation per filetype - I had to google that as well. I think overall it took me over an hour just to get a correctly indented TOC.

**Comment by huntertran** [comment]
maybe that the job for a formatting plugin like [Beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) or [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)?
Prettier documentation for support markdown [here](https://prettier.io/docs/en/index.html)
