### ISSUE TITLE
 command 'extension.updateMarkdownToc' not found

### ISSUE THREAD

**Issue by Nabav** [huntertran/markdown-toc#34]
I see this :point_down: and TOC is not generated.

> Command 'Auto Markdown TOC: Insert/Update' resulted in an error (command 'extension.updateMarkdownToc' not found)

Version: 1.44.1
OS: Linux x64 4.9.0-12-amd64

**Comment by huntertran** [comment]
which version are you using, on which platform.
Could you try again with version 3.0.9 preview?

**Comment by Nabav** [comment]
Extension v3.0.9 on vscode 1.46.1 tested successfully. Thanks.
