### ISSUE TITLE
Extension is not working

### ISSUE THREAD

**Issue by lc-soft** [huntertran/markdown-toc#35]
![Peek 2020-04-30 14-58](https://user-images.githubusercontent.com/1730073/80681412-3ccd6080-8af3-11ea-9361-d30968ab2a35.gif)

**VSCode:**

Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-42-generic

**Comment by Ian-T-Price** [comment]
I'm finding the same issue.  It worked (with issues) when I first loaded the extension but on a restart of VSCode nothing happens.

The issues I allude to are:
- All the commands in the right click menu were duplicated - that caused me to finally restart VSC which corrected the menu but nothing works...
- Inserting a ToC works but it is all on one line with the word 'auto' inserted where a newline should apprear.  Easy enough to fix with find and replace

**Comment by huntertran** [comment]
could you try to remove the extension then install it again?

**Comment by lc-soft** [comment]
@huntertran Sorry, it not work. 

I switched this extension to version 3.0.3 and it worked.

**Comment by huntertran** [comment]
I think I found the problem. The Linux file names are case sensitive.
I update the extension to 3.0.8. Please check if it works.
Thanks

**Comment by lc-soft** [comment]
I think this problem has existed since version 3.0.4, Because version 3.0.3 works normally, but after switching to version 3.0.4 it does not work.

**Comment by lc-soft** [comment]
I found that the version tags of this repository has not been updated since v2.2.2, I suggest that you add a tag every time you release a new version for this extension. so that you can easily use the following link to compare the differences between the two versions.

https://github.com/huntertran/markdown-toc/compare/v3.0.3...v3.0.4

**Comment by huntertran** [comment]
> I found that [the version tags of this repository](https://github.com/huntertran/markdown-toc/releases) has not been updated since v2.2.2, I suggest that you add a tag every time you release a new version for this extension. so that you can easily use the following link to compare the differences between the two versions.
> 
> [v3.0.3...v3.0.4](https://github.com/huntertran/markdown-toc/compare/v3.0.3...v3.0.4)

haha that exactly what I'm doing now

**Comment by n-alex-white** [comment]
I'm on MacOS, I try to run the command and it fails with the following message and no other information.

`Running the contributed command: 'extension.updateMarkdownToc' failed.`

**Comment by huntertran** [comment]
> I'm on MacOS, I try to run the command and it fails with the following message and no other information.
> 
> `Running the contributed command: 'extension.updateMarkdownToc' failed.`

which version are you using?

**Comment by J-Siu** [comment]
I am on MacOS also.
VSCode 1.46.1
Auto Markdown TOC is v3.0.9.

Seeing same issue. If I type the tag manually:

```html
<!-- TOC -->

<!-- /TOC -->
```

Then use the context menu to update, the above tag will disappear.

**Comment by huntertran** [comment]
@J-Siu can you share the simplified version of the markdown document? I'm testing on version 3.0.9 of the extension. As soon as I pasted the tags, the TOC appeared as expected

**Comment by J-Siu** [comment]
@huntertran 

I installed 3.0.10 and same result. My README.md is in repo: https://github.com/J-Siu/hugo-theme-sk3

Seems I found the cause from .md side. Issue happen if md file don't have L1 heading(#). You can try with following:

```md
## t21
## t22
## t23
### t31
## t24
```

It will work after adding a fake L1 heading:

```md
# t
```

But that is annoying.

**Comment by huntertran** [comment]
@J-Siu please try again with version 3.0.11

**Comment by J-Siu** [comment]
@huntertran yes 3.0.11 is working!
