### ISSUE TITLE
Percent Encoding is done at Japanese characters (not ASCII)

### ISSUE THREAD

**Issue by benibana2001** [huntertran/markdown-toc#36]
## Procedure I did

1. Turn on VSCode and install Auto Markdown TOC. Each version is following:
  - MacOS: Mojave 10.14.5
  - VSCode: 1.46.0
  - Auto Markdown TOC: 3.0.5

2. Create `index.md` and write text including Japanese; like following:

```

# hello-h1

## hello-h2

### こんにちは-h3

```

3.  Execute "Auto Markdown TOC Insert/Update" from right-click on mouse.

## Expected Outcome

Output Japanese characters directly(not Encoding).

```
- [hello-h1](#hello-h1)
    - [hello-h2](#hello-h2)
        - [こんにちは-h3](#こんにちは-h3)
```

## Actual Outcome

Encoded characters were output unexpectedly.

```
- [hello-h1](#hello-h1)
    - [hello-h2](#hello-h2)
        - [こんにちは-h3](#%E3%81%93%E3%82%93%E3%81%AB%E3%81%A1%E3%81%AF-h3)
```

**Comment by huntertran** [comment]
For any non-ASCII character, the character needs to be encoded with URL encoding. This is required for many browsers to have the link and anchor tag work correctly.
