### ISSUE TITLE
Ignore option does not work

### ISSUE THREAD

**Issue by leranjun** [huntertran/markdown-toc#40]
I've seen the documentation and #23, but am still confused about how I can ignore a header.

This is how it currently renders my document:
```markdown
<!-- TOC ignore:true -->
# Table of Contents
<!-- TOC -->
- [Table of Contents](#table-of-contents)
- [Part 1](#part-1)
<!-- /TOC -->

# Part 1
Some content here.
```

However, what I wish to do is this:
```markdown
<!-- TOC ignore:true -->
# Table of Contents
<!-- TOC -->
- [Part 1](#part-1)
<!-- /TOC -->

# Part 1
Some content here.
```

I can achieve that by using `<h1>` manually, but it's kind of annoying.

Any ideas how to solve that?

**Comment by huntertran** [comment]
I'm investigating this issue

**Comment by huntertran** [comment]
I think this is fixed in v3.0.12

**Comment by leranjun** [comment]
Thanks! When will this version be released to the marketplace?

**Comment by huntertran** [comment]
It is published now. Maybe 1-2 hours more.

**Comment by leranjun** [comment]
Hmm, it seems like there is another bug.

How do I put this...

Say, I have this document:
```markdown
<!-- TOC ignore:true -->
# Table of Contents
<!-- TOC orderedlist:true -->
- [Part 1](#part-1)
<!-- /TOC -->

# Part 1
Some content here.
```

When I click update from the context menu, it automatically becomes this:
```markdown
<!-- TOC ignore:true -->
# Table of Contents
<!-- TOC -->
- [Part 1](#part-1)
<!-- /TOC -->

# Part 1
Some content here.
```
And it does not change to an ordered list. It just ignores my setting.

Any idea how to solve that other than manually removing the ignored header and adding it back afterwards?

**Comment by huntertran** [comment]
This is because the extension cannot differentiate the first  with . So you will need to set up in a way that the  line should be in the document before any headings
