### ISSUE TITLE
Should strip « and » special characters from anchor

### ISSUE THREAD

**Issue by thierryseegers** [huntertran/markdown-toc#43]
I have section titles that are the form `« Example »` and GitHub drops the `«` and `»` characters from the link it generates for those, like it does for other special characters.

See here: https://github.com/thierryseegers/DevCommeLesPros-2021-Exo1/blob/master/README.md
markdown-toc generates: https://github.com/thierryseegers/DevCommeLesPros-2021-Exo1/blob/master/README.md#%C2%ABjai-un-probl%C3%A8me-%C2%BB
GitHub generates: https://github.com/thierryseegers/DevCommeLesPros-2021-Exo1/blob/master/README.md#jai-un-probl%C3%A8me-

The UTF-8 values for those characters are `%C2%AB` and `%C2%BB`.

**Comment by huntertran** [comment]
Thank you for this suggestion, but I think maintaining a list of special characters to be removed will not add any benefit to the plugin. The generated link is still working fine.
For example, `«` is truly a special character, as well as `ὣ`. If `«` is on the list, why not `ὣ`?

**Comment by thierryseegers** [comment]
But that's the thing, the generated link *doesn't* work because of it. If you clicked on what I wrote above thinking that it worked, it didn't. It only brought you the project's page, not the section that link refers to. You can compare the two links and see that the GitHub generated one brings you directly to that section.

Also, I agree with you that it would a pain to maintain some kind of "black list". I don't know if there's a simple rule that GitHub has for which character it keeps and which it doesn't...

**Comment by huntertran** [comment]
This is what I saw on both links
![image](https://user-images.githubusercontent.com/4468525/103668744-71789e00-4f45-11eb-874e-949261b4f869.png)
Is it a private repo? Do you have any public repo with the same issue so I can check?

**Comment by huntertran** [comment]
closed due to inactivities
