### ISSUE TITLE
Feature request: Configuration for number of spaces for list indentation 

### ISSUE THREAD

**Issue by OctagonHex** [huntertran/markdown-toc#45]
Hello,
In our repository we use a linter that has an expected indentation of 2 spaces. (I can't change that policy.) However, this plug-in always generates 4 spaces for the indentation of the unordered list. So either have to live with the warning, or change the indentation manually after every update.

So my feature request is: can you please add an setting that allows the user to change the default number of spaces for the indentation of the unordered list for the TOC?

**Comment by huntertran** [comment]
I've added this to [README ](https://github.com/huntertran/markdown-toc/blob/master/README.md) ;-)
