### ISSUE TITLE
Running the contributed command failed

### ISSUE THREAD

**Issue by pauby** [huntertran/markdown-toc#5]
Whenever I try to use the extension, using the Control-M T command I get this error:

```
Running the contributed command: 'extension.updateMarkdownToc' failed.
```

Note when I right-click and select `Auto Markdown-TOC: Insert/Update` from the menu I don't get the error, but nothing actually happens.

I've made sure the AlanWalk extension is actually uninstalled (just in case). ANd I've uninstalled and reinstalled this extension.

**Comment by huntertran** [comment]
Could you share the markdown file that cause error?


> 
> 
> Whenever I try to use the extension, using the Control-M T command I get this error:
> 
> ```
> Running the contributed command: 'extension.updateMarkdownToc' failed.
> ```
> 
> Note when I right-click and select `Auto Markdown-TOC: Insert/Update` from the menu I don't get the error, but nothing actually happens.
> 
> I've made sure the AlanWalk extension is actually uninstalled (just in case). ANd I've uninstalled and reinstalled this extension.

**Comment by huntertran** [comment]
never mind, found the issue, fixed the issue. Could you please test again with version 2.1.4?

**Comment by pauby** [comment]
I tried it on exactly the same markdown document (wioth 2.1.4) and worked right away! Awesome work!!
