### ISSUE TITLE
Does not work if a header starts with numbers

### ISSUE THREAD

**Issue by mlibre** [huntertran/markdown-toc#51]
If a header would be like:
```bash
# 8G tmpFs
```

The created ToC is:
```
- [G tmpFs](#g-tmpfs)
```

**Comment by huntertran** [comment]
for this to work correctly you may need to disable auto numbering

**Comment by soroshsabz** [comment]
@huntertran what is exact configuration name?

I cannot find this config in auto complete settings about "markdown-toc"
